### ISSUE TITLE
A player can see their hand of cards

### ISSUE THREAD

**Issue by tycobbb** [ZBASH/onitama#6]
For now, each player is dealt 2 cards, as a player always has two playable cards at any point in time.

## Tasks
- [x] Load the deck of cards on from JSON
- [x] Draw a hand of cards for each player (3 for first player, 2 for second player)
- [ ] Show the hand of cards for the player next to the board
